version: '3'
services:
  nlab-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src/:/app/src/
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
